export const languages = {
  en: "English",
  fr: "Français",
} as const;

export const defaultLang = "en" as const;

export type Lang = keyof typeof languages;

export const ui = {
  en: {
    // Navigation
    "nav.examples": "Examples",
    "nav.articles": "Articles",
    "nav.resources": "Resources",
    "nav.aiContext": "AI Context",

    // Header
    "header.title": "The Good, The Bad and The UX",
    "header.tagline": "A collection of UX patterns with comparative examples",
    "header.githubAriaLabel": "View on GitHub",

    // Footer
    "footer.openSource": "Open source project - Want to contribute?",
    "footer.contributeGithub": "Contribute on GitHub",
    "footer.suggestPattern": "Suggest a pattern",
    "footer.madeBy": "Made by Clément Bouly",

    // Common
    "common.new": "New",
    "common.all": "All",
    "common.share": "Share",
    "common.copied": "Copied!",
    "common.learnMore": "Learn more",
    "common.backToHome": "Back to home",
    "common.search": "Search",

    // Examples
    "example.bad": "Bad example",
    "example.good": "Good example",
    "example.multipleGood": "Multiple good examples!",
    "example.notFound": "Example not found",
    "example.backToAll": "Back to all examples",
    "example.backToCategory": "Back to {category}",
    "example.publishedOn": "Published on",
    "example.exploreMore": "Explore more examples",
    "example.viewExample": "View example",

    // Search / Command Menu
    "search.placeholder": "Search...",
    "search.ariaLabel": "Search",
    "search.dialogTitle": "Search examples and articles",
    "search.dialogDescription": "Search for UX patterns and examples",
    "search.noResults": "No examples found.",
    "search.groupExamples": "Examples",
    "search.groupArticles": "Articles",

    // 404
    "notFound.title": "Page not found",
    "notFound.message1": "This cat looked everywhere. The page is gone.",
    "notFound.message2": "Even our best algorithms couldn't find this page.",
    "notFound.message3": "This page went on vacation. Without leaving a forwarding address.",
    "notFound.message4": "404: Page playing hide and seek. It's winning.",
    "notFound.message5": "The page you're looking for is in another castle.",
    "notFound.message6": "Oops! This page got mass layoff'd.",

    // Theme
    "theme.switchToDark": "Switch to dark mode",
    "theme.switchToLight": "Switch to light mode",

    // Articles page
    "articles.title": "Articles",
    "articles.description": "In-depth guides combining multiple UX patterns",
    "articles.readArticle": "Read article",
    "articles.empty": "No articles yet. Check back soon!",
    "articles.backToArticles": "Back to articles",

    // Resources page
    "resources.title": "Resources",
    "resources.description": "Curated collection of UX resources to level up your skills",
    "resources.empty": "No resources yet. Check back soon!",

    // AI page
    "ai.title": "AI Context",
    "ai.whatIsThis": "What is this?",
    "ai.howToUse": "How to use",
    "ai.copyLink": "Copy Link",
    "ai.copyContent": "Copy Content",
    "ai.download": "Download",
    "ai.tagline": "Give your AI coding assistant UX superpowers",
    "ai.description1":
      "A single file containing all the UX best practices from this site, formatted for AI assistants. When you provide this as context, your AI will automatically apply good UX patterns when generating UI components.",
    "ai.description2Before": "Instead of asking",
    "ai.description2Example1": "create a user list with skeleton loading",
    "ai.description2Middle": ", just ask",
    "ai.description2Example2": "create a user list",
    "ai.description2After": "— the AI will know to use skeletons instead of spinners.",
    "ai.step1Title": "If your AI can read URLs",
    "ai.step1Description":
      "Just give it the link. Works with Claude, ChatGPT with browsing, and similar tools.",
    "ai.step2Title": "If you need to paste the content",
    "ai.step2Description":
      "Copy the full content and paste it in your conversation or project context (Cursor rules, Claude project, etc.)",
    "ai.step3Title": "If you prefer a local file",
    "ai.step3Description":
      "Download the file and add it to your project's context (e.g., .cursorrules, CLAUDE.md, etc.)",
    "ai.autoGenerated":
      "The file is auto-generated from all patterns and articles on this site. It updates automatically when new content is added.",

    // Mobile nav
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "nav.github": "GitHub",

    // Language
    "lang.switchTo": "Switch to {lang}",
    "lang.currentLanguage": "Current language: {lang}. Click to change.",
  },
  fr: {
    // Navigation
    "nav.examples": "Exemples",
    "nav.articles": "Articles",
    "nav.resources": "Ressources",
    "nav.aiContext": "Contexte IA",

    // Header
    "header.title": "The Good, The Bad and The UX",
    "header.tagline": "Une collection de patterns UX avec des exemples comparatifs",
    "header.githubAriaLabel": "Voir sur GitHub",

    // Footer
    "footer.openSource": "Projet open source - Envie de contribuer ?",
    "footer.contributeGithub": "Contribuer sur GitHub",
    "footer.suggestPattern": "Suggérer un pattern",
    "footer.madeBy": "Créé par Clément Bouly",

    // Common
    "common.new": "Nouveau",
    "common.all": "Tout",
    "common.share": "Partager",
    "common.copied": "Copié !",
    "common.learnMore": "En savoir plus",
    "common.backToHome": "Retour à l'accueil",
    "common.search": "Rechercher",

    // Examples
    "example.bad": "Mauvais exemple",
    "example.good": "Bon exemple",
    "example.multipleGood": "Plusieurs bons exemples !",
    "example.notFound": "Exemple non trouvé",
    "example.backToAll": "Retour aux exemples",
    "example.backToCategory": "Retour à {category}",
    "example.publishedOn": "Publié le",
    "example.exploreMore": "Découvrir d'autres exemples",
    "example.viewExample": "Voir l'exemple",

    // Search / Command Menu
    "search.placeholder": "Rechercher...",
    "search.ariaLabel": "Rechercher",
    "search.dialogTitle": "Rechercher exemples et articles",
    "search.dialogDescription": "Rechercher des patterns et exemples UX",
    "search.noResults": "Aucun exemple trouvé.",
    "search.groupExamples": "Exemples",
    "search.groupArticles": "Articles",

    // 404
    "notFound.title": "Page non trouvée",
    "notFound.message1": "Ce chat a cherché partout. La page a disparu.",
    "notFound.message2": "Même nos meilleurs algorithmes n'ont pas trouvé cette page.",
    "notFound.message3": "Cette page est partie en vacances. Sans laisser d'adresse.",
    "notFound.message4": "404 : La page joue à cache-cache. Elle gagne.",
    "notFound.message5": "La page que vous cherchez est dans un autre château.",
    "notFound.message6": "Oups ! Cette page a été licenciée.",

    // Theme
    "theme.switchToDark": "Passer en mode sombre",
    "theme.switchToLight": "Passer en mode clair",

    // Articles page
    "articles.title": "Articles",
    "articles.description": "Guides approfondis combinant plusieurs patterns UX",
    "articles.readArticle": "Lire l'article",
    "articles.empty": "Pas encore d'articles. Revenez bientôt !",
    "articles.backToArticles": "Retour aux articles",

    // Resources page
    "resources.title": "Ressources",
    "resources.description": "Collection de ressources UX pour améliorer vos compétences",
    "resources.empty": "Pas encore de ressources. Revenez bientôt !",

    // AI page
    "ai.title": "Contexte IA",
    "ai.whatIsThis": "Qu'est-ce que c'est ?",
    "ai.howToUse": "Comment utiliser",
    "ai.copyLink": "Copier le lien",
    "ai.copyContent": "Copier le contenu",
    "ai.download": "Télécharger",
    "ai.tagline": "Donnez des super pouvoirs UX à votre assistant IA",
    "ai.description1":
      "Un fichier unique contenant toutes les bonnes pratiques UX de ce site, formaté pour les assistants IA. Lorsque vous fournissez ce contexte, votre IA appliquera automatiquement les bons patterns UX lors de la génération de composants UI.",
    "ai.description2Before": "Au lieu de demander",
    "ai.description2Example1": "crée une liste d'utilisateurs avec un skeleton loading",
    "ai.description2Middle": ", demandez simplement",
    "ai.description2Example2": "crée une liste d'utilisateurs",
    "ai.description2After": "— l'IA saura utiliser des skeletons plutôt que des spinners.",
    "ai.step1Title": "Si votre IA peut lire les URLs",
    "ai.step1Description":
      "Donnez-lui simplement le lien. Fonctionne avec Claude, ChatGPT avec navigation, et outils similaires.",
    "ai.step2Title": "Si vous devez coller le contenu",
    "ai.step2Description":
      "Copiez le contenu complet et collez-le dans votre conversation ou contexte de projet (Cursor rules, projet Claude, etc.)",
    "ai.step3Title": "Si vous préférez un fichier local",
    "ai.step3Description":
      "Téléchargez le fichier et ajoutez-le au contexte de votre projet (ex: .cursorrules, CLAUDE.md, etc.)",
    "ai.autoGenerated":
      "Le fichier est généré automatiquement à partir de tous les patterns et articles de ce site. Il se met à jour automatiquement quand du nouveau contenu est ajouté.",

    // Mobile nav
    "nav.openMenu": "Ouvrir le menu",
    "nav.closeMenu": "Fermer le menu",
    "nav.github": "GitHub",

    // Language
    "lang.switchTo": "Passer en {lang}",
    "lang.currentLanguage": "Langue actuelle : {lang}. Cliquez pour changer.",
  },
} as const;
