export const countries = [
  { code: "US", name: "United States", nameFr: "États-Unis" },
  { code: "GB", name: "United Kingdom", nameFr: "Royaume-Uni" },
  { code: "FR", name: "France", nameFr: "France" },
  { code: "DE", name: "Germany", nameFr: "Allemagne" },
  { code: "ES", name: "Spain", nameFr: "Espagne" },
  { code: "IT", name: "Italy", nameFr: "Italie" },
  { code: "PT", name: "Portugal", nameFr: "Portugal" },
  { code: "NL", name: "Netherlands", nameFr: "Pays-Bas" },
  { code: "BE", name: "Belgium", nameFr: "Belgique" },
  { code: "CH", name: "Switzerland", nameFr: "Suisse" },
  { code: "AT", name: "Austria", nameFr: "Autriche" },
  { code: "SE", name: "Sweden", nameFr: "Suède" },
  { code: "NO", name: "Norway", nameFr: "Norvège" },
  { code: "DK", name: "Denmark", nameFr: "Danemark" },
  { code: "FI", name: "Finland", nameFr: "Finlande" },
  { code: "PL", name: "Poland", nameFr: "Pologne" },
  { code: "CA", name: "Canada", nameFr: "Canada" },
  { code: "AU", name: "Australia", nameFr: "Australie" },
  { code: "NZ", name: "New Zealand", nameFr: "Nouvelle-Zélande" },
  { code: "JP", name: "Japan", nameFr: "Japon" },
  { code: "KR", name: "South Korea", nameFr: "Corée du Sud" },
  { code: "CN", name: "China", nameFr: "Chine" },
  { code: "IN", name: "India", nameFr: "Inde" },
  { code: "BR", name: "Brazil", nameFr: "Brésil" },
  { code: "MX", name: "Mexico", nameFr: "Mexique" },
  { code: "AR", name: "Argentina", nameFr: "Argentine" },
  { code: "ZA", name: "South Africa", nameFr: "Afrique du Sud" },
  { code: "AE", name: "United Arab Emirates", nameFr: "Émirats arabes unis" },
  { code: "SG", name: "Singapore", nameFr: "Singapour" },
  { code: "IE", name: "Ireland", nameFr: "Irlande" },
];
